% Template for all the parameters
function [params, Visparams, CVG]=tryDefaults()

params=struct('FilterParams' , struct('notch',    struct([]),...
                             'zapline',  struct([]),...
                             'high',     struct([]),...
                             'low',      struct([]), ...
                             'firws',    struct([])),...   
                         'CRDParams' , struct([]),...             % Clean raw data parameters
         'PrepParams' , struct(),...
        'HighvarParams' , struct([]),...
         'MinvarParams' , struct([]),...
         'InterpolationParams' , struct('method', 'spherical'),...
        'RPCAParams' , struct([]),...
        'MARAParams' , struct([]),...
         'TrimDataParams' , struct(),...
        'TrimOutlierParams' , struct(),...
         'ICLabelParams' , struct('brainTher', [], ...
                               'muscleTher', 0.8, ...
                               'eyeTher', 0.8, ...
                               'heartTher', 0.8, ...
                               'lineNoiseTher', 0.8, ...
                               'channelNoiseTher', 0.8, ...
                               'otherTher', [], ...
                               'includeSelected', 0, ...
                               'keep_comps', 0, ...
                               'high',     struct('freq', 2.0,...
                                                  'order', [])),...
                     'EOGRegressionParams' , struct(),...
                        'ChannelReductionParams' , struct(),...
         'DetrendingParams' , struct([]),...
                                       'EEGSystem' , struct('name', 'Others',...
                           'sys10_20', 0, ...
                           'locFile', '', ...
                           'refChan', [], ...
                           'fileLocType', '',...
                           'eogChans', [],...
                           'powerLineFreq', []),...          
                      'Settings' , struct('trackAllSteps', 0,...
                          'colormap','Default'));
  
                      
                      
Visparams=struct('COLOR_SCALE' , 100,...
        'dsRate' , 2,...
        'CalcQualityParams' , struct('overallThresh',    20:5:40, ...
                                    'timeThresh',       5:5:25,...
                                    'chanThresh',       5:5:25,...   
                                    'avRef',            1),...
                                    'RateQualityParams' , struct('overallGoodCutoff',   0.1,...
                                     'overallBadCutoff',    0.2,... 
                                     'timeGoodCutoff',      0.1,...
                                     'timeBadCutoff',       0.2,...                                        
                                     'channelGoodCutoff',   0.15,...
                                     'channelBadCutoff',    0.3,...   
                                     'BadChannelGoodCutoff',0.15,...
                                     'BadChannelBadCutoff', 0.3,...  
                                     'Qmeasure',['THV','OHA','CHV','RBC']));
  
CVG=ConstantGlobalValues();